title: "Hongyu (Dennis) Feng"
author: "Hongyu (Dennis) Feng"
description: "JOHNS HOPKINS UNIVERSITY"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true 
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "/HFeng.github.io/Hongyu-Dennis-CV-august.pdf", title: "CV"}
  - {file: "/HFeng.github.io/Transcript_HONGYUFENG.pdf",  title: "Transcript"}
  - {url: "https://www.linkedin.com/in/hongyu-dennis-feng-3799251a4/",  title: "LinkedIn"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
